name: secrets_workflow
on:
  workflow_dispatch:
jobs:
  login:
    runs on: ubuntu-latest
    steps:
    - name: LOGGING INTO DOCKERHUB
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKERHUB.USERNAME}}
        password: ${{secrets.DOCKERHUB.PASSWORD}}
